### ISSUE TITLE
Address score card issues

### ISSUE THREAD

**Issue by larseggert** [mozilla/neqo#1822]
Address some of the issues identified in https://securityscorecards.dev/viewer/?uri=github.com/mozilla/neqo&sort_by=risk-level&sort_direction=desc

E.g., we're scoring low on:
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/neqo/issues/1841
- [ ] https://github.com/mozilla/neqo/issues/1840
- [ ] https://github.com/mozilla/neqo/issues/1843
- [ ] https://github.com/mozilla/neqo/issues/1844
- [ ] https://github.com/mozilla/neqo/issues/1842
```

**Comment by larseggert** [comment]
We're at 8.8 now - good enough.
